### PR TITLE
modify /bin/setup to Install Redis

### PR DESCRIPTION
**Pull request by abhinaykumar**
running OS specific commands to Install Redis.

### CODE REVIEW

**Comment by syndbg** [comment]
You did not take into account the README.md line `Note: You must have Ruby 2.2.2 installed in order to use redis`.

To do so, add a check `Gem::Version.new(RUBY_VERSION) < Gem::Version.new('2.2.2') `

**Comment by dhh** [comment]
I know I proposed this, but I'm having second thoughts. I think maybe we should just stay with install instructions as is. Don't want to have to promise this to work on all sorts of platforms and with their dependencies. Thanks for proving this out, though!

**Comment by abhinaykumar** [comment]
@syndbg Thanks for pointing it out, I completely missed it.

**Comment by abhinaykumar** [comment]
@dhh Thank you for looking at it, I agree with your thoughts. Even though I have tested it on Ubuntu and Mac osx Yosemite, it was working fine but as @syndbg mentioned I was completely missing the point here that Ruby 2.2.2 should be installed which was there in my case. :+1:

**Pull request closed without merging**
