### PR TITLE
Revamp example app to use Rails 7

### PR DESCRIPTION
**Pull request by julianfssen**
Hey, there!

# Problem

I read the Rails Action Cable guide and [saw a section mentioning this project as a fullstack example](https://guides.rubyonrails.org/action_cable_overview.html#more-complete-examples). However, I wasn't able to run the project locally as I had issues installing the `sqlite3` gem in my Mac (ARM). 

I also noticed the project was using Rails 5 and used legacy code that no longer exists (or recommended) in Rails 7.

# Solution

I updated the app to use Rails 7, as well as updating the business logic to follow modern Rails conventions (e.g. using Turbo, use `subscribed` / `unsubscribed` when implementing channels, etc.).

This makes it easier for readers to explore and try out the example app, as well as integrating Action Cable in their current Rails app.

# Changes
## Updated
* Updated app to use `ruby "3.2.2"`
* Updated app to use `"rails", "~> 7.0.6"`
* Updated app to use `importmap`
* Updated app to use `sprockets-rails` for asset pipelining
* Updated setup instructions and live `gif` example in `README`
* Updated `CommentsChannel` to use the `subscribed` and `unsubscribed` actions convention when creating subscriptions
* Updated `CommentsController#create` and its respective view to use Turbo streams
* Updated the client-side `comments_channel.js` controller's methods to match the current Rails convention
* Updated `CommentsChannel` to only create subscriptions on `MessagesController#show` via `javascript_import_module_tag`
* Updated the app to use the `async` adapter for local Action Cable connections and streams.
* Updated config files to use Rails 7 defaults

## Added
* Added unit, controller, and system tests for `Comment` and `CommentsChannel`.

## Removed
* Removed the following outdated gems: `coffee-rails`, `jquery-rails` `sass-rails`, `turbolink`, `uglifier`
* Removed instructions to install `redis` in `README`

# Notes
* I've not yet squashed the commits in this PR for reference purposes. If the PR is approved, I'll squash the commits before merging into `main`.
* I added a monkey-patch for a test here (https://github.com/rails/actioncable-examples/compare/master...julianfssen:actioncable-examples:update-example-to-rails7?expand=1#diff-02f5247d15b5423e1c7a9eda292340dc17beea31f870a8878a5d1d2811997159R28), which I'll create a PR for in the `rails` repo.

---

Thank you so much for the review!

### CODE REVIEW

**Comment by julianfssen** [comment]
Good day, ~~kaspth , guilleiguaran~~!

I saw you were involved in merging PRs for the example app. Do you mind helping me out with my PR above and see if it's good to be merged in?

I understand it's been a _very_ long time (5 years!) since you were involved this repo, so I apologize if you're no longer involved in updating the project.

Thank you and have a great day ahead!

**Comment by julianfssen** [comment]
Good day, everybody! 

I was wondering if there's interest in merging this to `main`? I think it's valuable for readers to see how `ActionCable` is implemented in a modern Rails app, since we've updated several `rails` and `ActionCable`-related conventions since then.

Thank you again!

**Comment by julianfssen** [comment]
Good morning, @dhh ! 

As mentioned above, I've updated this repo [which is linked in the Action Cable guide](https://guides.rubyonrails.org/action_cable_overview.html#more-complete-examples) to be up to date with Rails 7.

However, I'm not sure if this repo is still in use. If it is, would you be able to review this and see if it's worth merging? 

Feel free to let me know if it should be reviewed by another maintainer or if we're no longer using this repo.

Thank you and have a great week ahead!

**Comment by dhh** [comment]
Appreciate the work on this, but no, it's no longer meant to be kept active. We should update the guide to stop pointing here, and instead incorporate the lessons directly into the guide.

**Pull request closed without merging**
